function [ outdata ] = spatialize_bin( SPAT, audiodata, az, el )
%SPATIALIZE spatialize a sound at given azimuth and elevation
%   Requires the SPAT structure generated by spat_init
%   if el is not given, assume el=0

narginchk(3, 4);
if nargin==3
    el = 0;
end

if isAudio(audiodata)
    if ~isvector(audiodata.data)
        error('Input must be single-channel.')
    end
    outAudio = true;
else
    if ~isvector(audiodata)
        error('Input must be single-channel.')
    end
    audiodata = genAudio(audiodata, SPAT.fs);
    outAudio = false;
end

if audiodata.fs ~= SPAT.fs
    error('Sampling rate mismatch.');
end

%%%%%%%%%%%%%%%%

hrir = SPAT.loadHRIRfun(az, el);
outdata = fftfilt(hrir, audiodata.data);
if outAudio
    outdata = genAudio(outdata, SPAT.fs);
end

end

